"""append text_align in cell

Revision ID: 008369da58f2
Revises: 2c7aefb7ec0d
Create Date: 2023-07-13 14:46:59.158725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008369da58f2'
down_revision = '2c7aefb7ec0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_cell', sa.Column('text_align', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_cell', 'text_align')
    # ### end Alembic commands ###
