"""drop report_fc from interval

Revision ID: 146bdf6c8688
Revises: 427fcd64fd67
Create Date: 2023-06-16 19:40:23.524137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146bdf6c8688'
down_revision = '427fcd64fd67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interval_report_id_fkey', 'interval', type_='foreignkey')
    op.drop_column('interval', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('interval_report_id_fkey', 'interval', 'report', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
