"""change report model

Revision ID: 1af6b2164975
Revises: 146bdf6c8688
Create Date: 2023-06-16 19:44:15.690283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af6b2164975'
down_revision = '146bdf6c8688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('interval_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'report', ['interval_id'])
    op.create_foreign_key(None, 'report', 'interval', ['interval_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='unique')
    op.drop_column('report', 'interval_id')
    # ### end Alembic commands ###
