"""append is_readonly to sindex

Revision ID: 2c7aefb7ec0d
Revises: 9b8e5f881b4b
Create Date: 2023-07-13 10:58:44.307699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7aefb7ec0d'
down_revision = '9b8e5f881b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_col', sa.Column('is_readonly', sa.Boolean(), nullable=False))
    op.add_column('sheet_row', sa.Column('is_readonly', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_row', 'is_readonly')
    op.drop_column('sheet_col', 'is_readonly')
    # ### end Alembic commands ###
