"""sub1

Revision ID: 3c24ca78e3e5
Revises: 9a86d42a4063
Create Date: 2023-08-20 14:59:25.032042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c24ca78e3e5'
down_revision = '9a86d42a4063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wire', sa.Column('sub1', sa.String(length=800), nullable=True))
    op.add_column('wire', sa.Column('sub2', sa.String(length=800), nullable=True))
    op.drop_column('wire', 'subconto_second')
    op.drop_column('wire', 'subconto_first')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wire', sa.Column('subconto_first', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
    op.add_column('wire', sa.Column('subconto_second', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
    op.drop_column('wire', 'sub2')
    op.drop_column('wire', 'sub1')
    # ### end Alembic commands ###
