"""sheet_id

Revision ID: 3e87577e9c9c
Revises: 7aa3d829bf3d
Create Date: 2023-06-15 17:52:31.670911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e87577e9c9c'
down_revision = '7aa3d829bf3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('sheet_id', sa.String(length=30), nullable=False))
    op.drop_constraint('report_sheet_key', 'report', type_='unique')
    op.create_unique_constraint(None, 'report', ['sheet_id'])
    op.drop_column('report', 'sheet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('sheet', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report', type_='unique')
    op.create_unique_constraint('report_sheet_key', 'report', ['sheet'])
    op.drop_column('report', 'sheet_id')
    # ### end Alembic commands ###
