"""report init

Revision ID: 4615eb23a26f
Revises: f4aaa7f70a00
Create Date: 2023-06-15 11:16:39.670726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4615eb23a26f'
down_revision = 'f4aaa7f70a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('source_base', sa.Integer(), nullable=False),
    sa.Column('sheet', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_base'], ['source_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('source_base', sa.Integer(), nullable=False),
    sa.Column('sheet', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_base'], ['source_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet')
    )
    op.create_table('interval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_day', sa.Integer(), nullable=False),
    sa.Column('report', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interval')
    op.drop_table('report')
    op.drop_table('group')
    op.drop_table('category')
    # ### end Alembic commands ###
