"""change sheet_cell table

Revision ID: 482f86fbe231
Revises: 104e6f245251
Create Date: 2023-06-18 11:26:40.079358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f86fbe231'
down_revision = '104e6f245251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_cell', sa.Column('is_index', sa.Boolean(), nullable=False))
    op.add_column('sheet_cell', sa.Column('color', sa.String(length=16), nullable=True))
    op.add_column('sheet_cell', sa.Column('row_id', sa.Integer(), nullable=False))
    op.add_column('sheet_cell', sa.Column('col_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sheet_cell', 'sheet_col', ['col_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sheet_cell', 'sheet_row', ['row_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sheet_cell', type_='foreignkey')
    op.drop_constraint(None, 'sheet_cell', type_='foreignkey')
    op.drop_column('sheet_cell', 'col_id')
    op.drop_column('sheet_cell', 'row_id')
    op.drop_column('sheet_cell', 'color')
    op.drop_column('sheet_cell', 'is_index')
    # ### end Alembic commands ###
