"""init

Revision ID: 59f2f14c4ac2
Revises: 
Create Date: 2023-06-18 11:46:35.432145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f2f14c4ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('total_start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('total_end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('wcols', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('sender', sa.Float(), nullable=False),
    sa.Column('receiver', sa.Float(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('subconto_first', sa.String(length=800), nullable=True),
    sa.Column('subconto_second', sa.String(length=800), nullable=True),
    sa.Column('comment', sa.String(length=800), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.String(length=30), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interval_id'], ['interval.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interval_id'),
    sa.UniqueConstraint('sheet_id')
    )
    op.create_table('interval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_col',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_freeze', sa.Boolean(), nullable=False),
    sa.Column('is_filtred', sa.Boolean(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('scroll_pos', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_freeze', sa.Boolean(), nullable=False),
    sa.Column('is_filtred', sa.Boolean(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('scroll_pos', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('dtype', sa.String(length=30), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_filtred', sa.Boolean(), nullable=False),
    sa.Column('is_index', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('col_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['col_id'], ['sheet_col.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['sheet_row.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet_cell')
    op.drop_table('sheet_row')
    op.drop_table('sheet_col')
    op.drop_table('sheet')
    op.drop_table('interval')
    op.drop_table('report')
    op.drop_table('group')
    op.drop_table('category')
    op.drop_table('wire')
    op.drop_table('source')
    # ### end Alembic commands ###
