"""checker1

Revision ID: 7b50bb3fa535
Revises: 3c24ca78e3e5
Create Date: 2023-09-03 12:12:52.615861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b50bb3fa535'
down_revision = '3c24ca78e3e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('checker_sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'sheet', ['checker_sheet_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'checker_sheet_id')
    # ### end Alembic commands ###
