"""indexes cell

Revision ID: 8fc7c228a85b
Revises: 97ab302b26f7
Create Date: 2023-06-22 17:30:04.827256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc7c228a85b'
down_revision = '97ab302b26f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sheet_cell_value'), 'sheet_cell', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_cell_value'), table_name='sheet_cell')
    # ### end Alembic commands ###
