"""indexes

Revision ID: 97ab302b26f7
Revises: 74a9bfd8a7be
Create Date: 2023-06-22 11:50:41.685352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ab302b26f7'
down_revision = '74a9bfd8a7be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sheet_cell_col_id'), 'sheet_cell', ['col_id'], unique=False)
    op.create_index(op.f('ix_sheet_cell_row_id'), 'sheet_cell', ['row_id'], unique=False)
    op.create_index(op.f('ix_sheet_cell_sheet_id'), 'sheet_cell', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_sheet_col_scroll_pos'), 'sheet_col', ['scroll_pos'], unique=False)
    op.create_index(op.f('ix_sheet_col_sheet_id'), 'sheet_col', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_sheet_row_scroll_pos'), 'sheet_row', ['scroll_pos'], unique=False)
    op.create_index(op.f('ix_sheet_row_sheet_id'), 'sheet_row', ['sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_row_sheet_id'), table_name='sheet_row')
    op.drop_index(op.f('ix_sheet_row_scroll_pos'), table_name='sheet_row')
    op.drop_index(op.f('ix_sheet_col_sheet_id'), table_name='sheet_col')
    op.drop_index(op.f('ix_sheet_col_scroll_pos'), table_name='sheet_col')
    op.drop_index(op.f('ix_sheet_cell_sheet_id'), table_name='sheet_cell')
    op.drop_index(op.f('ix_sheet_cell_row_id'), table_name='sheet_cell')
    op.drop_index(op.f('ix_sheet_cell_col_id'), table_name='sheet_cell')
    # ### end Alembic commands ###
