"""append text_align in lc

Revision ID: 9cf49691f785
Revises: c3aca86d5a9e
Create Date: 2023-07-13 14:59:09.453863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf49691f785'
down_revision = 'c3aca86d5a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
