"""Source base with autoinc

Revision ID: b00524fe80a6
Revises: dfba6ca35e67
Create Date: 2023-06-14 11:28:50.357718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00524fe80a6'
down_revision = 'dfba6ca35e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
