"""append text_align in cell drop nullable

Revision ID: c3aca86d5a9e
Revises: 008369da58f2
Create Date: 2023-07-13 14:51:28.712544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aca86d5a9e'
down_revision = '008369da58f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
