"""Source base with not nullable

Revision ID: dfba6ca35e67
Revises: e7fa32077ffb
Create Date: 2023-06-14 10:21:34.201990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfba6ca35e67'
down_revision = 'e7fa32077ffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_base', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('source_base', 'total_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('source_base', 'total_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('source_base', 'wcols',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_base', 'wcols',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('source_base', 'total_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('source_base', 'total_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('source_base', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
