"""append fixed columns

Revision ID: e3f2afc45e49
Revises: 29083eadd580
Create Date: 2023-07-19 13:36:12.100276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3f2afc45e49'
down_revision = '29083eadd580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('fixed_columns', sa.JSON(), nullable=False))
    op.drop_column('group', 'dynamic_columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('dynamic_columns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('group', 'fixed_columns')
    # ### end Alembic commands ###
