"""WireDbCreation

Revision ID: e7fa32077ffb
Revises: 
Create Date: 2023-06-13 19:01:13.311815

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e7fa32077ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_base',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=80), nullable=True),
                    sa.Column('total_start_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('total_end_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('wcols', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wire',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.TIMESTAMP(), nullable=False),
                    sa.Column('sender', sa.Float(), nullable=False),
                    sa.Column('receiver', sa.Float(), nullable=False),
                    sa.Column('debit', sa.Float(), nullable=False),
                    sa.Column('credit', sa.Float(), nullable=False),
                    sa.Column('subconto_first', sa.String(length=80), nullable=True),
                    sa.Column('subconto_second', sa.String(length=80), nullable=True),
                    sa.Column('comment', sa.String(length=80), nullable=True),
                    sa.Column('source_base_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['source_base_id'], ['source_base.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wire')
    op.drop_table('source_base')
    # ### end Alembic commands ###
