"""init

Revision ID: f4aaa7f70a00
Revises: 
Create Date: 2023-06-14 13:29:28.608215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aaa7f70a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('total_start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('total_end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('wcols', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('sender', sa.Float(), nullable=False),
    sa.Column('receiver', sa.Float(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('subconto_first', sa.String(length=800), nullable=True),
    sa.Column('subconto_second', sa.String(length=800), nullable=True),
    sa.Column('comment', sa.String(length=800), nullable=True),
    sa.Column('source_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_base_id'], ['source_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wire')
    op.drop_table('source_base')
    # ### end Alembic commands ###
